server:
    port: 7070

spring:
    profiles:
        active: prod
        
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
            
    jackson:
        serialization.indent_output: true
            
application: